//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EV4CristopherPeregrin.Cliente), "Prestamo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EV4CristopherPeregrin.Prestamo), true)]
[assembly: EdmRelationshipAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Libro", "Libro", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EV4CristopherPeregrin.Libro), "Prestamo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EV4CristopherPeregrin.Prestamo), true)]

#endregion

namespace EV4CristopherPeregrin
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EV4CristopherPeregrinEntidades : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EV4CristopherPeregrinEntidades usando la cadena de conexión encontrada en la sección 'EV4CristopherPeregrinEntidades' del archivo de configuración de la aplicación.
        /// </summary>
        public EV4CristopherPeregrinEntidades() : base("name=EV4CristopherPeregrinEntidades", "EV4CristopherPeregrinEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EV4CristopherPeregrinEntidades.
        /// </summary>
        public EV4CristopherPeregrinEntidades(string connectionString) : base(connectionString, "EV4CristopherPeregrinEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EV4CristopherPeregrinEntidades.
        /// </summary>
        public EV4CristopherPeregrinEntidades(EntityConnection connection) : base(connection, "EV4CristopherPeregrinEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Libro> Libro
        {
            get
            {
                if ((_Libro == null))
                {
                    _Libro = base.CreateObjectSet<Libro>("Libro");
                }
                return _Libro;
            }
        }
        private ObjectSet<Libro> _Libro;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Prestamo> Prestamo
        {
            get
            {
                if ((_Prestamo == null))
                {
                    _Prestamo = base.CreateObjectSet<Prestamo>("Prestamo");
                }
                return _Prestamo;
            }
        }
        private ObjectSet<Prestamo> _Prestamo;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Libro. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLibro(Libro libro)
        {
            base.AddObject("Libro", libro);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Prestamo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPrestamo(Prestamo prestamo)
        {
            base.AddObject("Prestamo", prestamo);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EV4CristopherPeregrinModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="clienteID">Valor inicial de la propiedad ClienteID.</param>
        public static Cliente CreateCliente(global::System.Int32 clienteID)
        {
            Cliente cliente = new Cliente();
            cliente.ClienteID = clienteID;
            return cliente;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                if (_ClienteID != value)
                {
                    OnClienteIDChanging(value);
                    ReportPropertyChanging("ClienteID");
                    _ClienteID = StructuralObject.SetValidValue(value, "ClienteID");
                    ReportPropertyChanged("ClienteID");
                    OnClienteIDChanged();
                }
            }
        }
        private global::System.Int32 _ClienteID;
        partial void OnClienteIDChanging(global::System.Int32 value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rut
        {
            get
            {
                return _Rut;
            }
            set
            {
                OnRutChanging(value);
                ReportPropertyChanging("Rut");
                _Rut = StructuralObject.SetValidValue(value, true, "Rut");
                ReportPropertyChanged("Rut");
                OnRutChanged();
            }
        }
        private global::System.String _Rut;
        partial void OnRutChanging(global::System.String value);
        partial void OnRutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombres
        {
            get
            {
                return _Nombres;
            }
            set
            {
                OnNombresChanging(value);
                ReportPropertyChanging("Nombres");
                _Nombres = StructuralObject.SetValidValue(value, true, "Nombres");
                ReportPropertyChanged("Nombres");
                OnNombresChanged();
            }
        }
        private global::System.String _Nombres;
        partial void OnNombresChanging(global::System.String value);
        partial void OnNombresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellidos
        {
            get
            {
                return _Apellidos;
            }
            set
            {
                OnApellidosChanging(value);
                ReportPropertyChanging("Apellidos");
                _Apellidos = StructuralObject.SetValidValue(value, true, "Apellidos");
                ReportPropertyChanged("Apellidos");
                OnApellidosChanged();
            }
        }
        private global::System.String _Apellidos;
        partial void OnApellidosChanging(global::System.String value);
        partial void OnApellidosChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Cliente", "Prestamo")]
        public EntityCollection<Prestamo> Prestamo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Prestamo>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Prestamo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Prestamo>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Prestamo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EV4CristopherPeregrinModel", Name="Libro")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Libro : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Libro.
        /// </summary>
        /// <param name="libroID">Valor inicial de la propiedad LibroID.</param>
        public static Libro CreateLibro(global::System.Int32 libroID)
        {
            Libro libro = new Libro();
            libro.LibroID = libroID;
            return libro;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LibroID
        {
            get
            {
                return _LibroID;
            }
            set
            {
                if (_LibroID != value)
                {
                    OnLibroIDChanging(value);
                    ReportPropertyChanging("LibroID");
                    _LibroID = StructuralObject.SetValidValue(value, "LibroID");
                    ReportPropertyChanged("LibroID");
                    OnLibroIDChanged();
                }
            }
        }
        private global::System.Int32 _LibroID;
        partial void OnLibroIDChanging(global::System.Int32 value);
        partial void OnLibroIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroSerie
        {
            get
            {
                return _NumeroSerie;
            }
            set
            {
                OnNumeroSerieChanging(value);
                ReportPropertyChanging("NumeroSerie");
                _NumeroSerie = StructuralObject.SetValidValue(value, true, "NumeroSerie");
                ReportPropertyChanged("NumeroSerie");
                OnNumeroSerieChanged();
            }
        }
        private global::System.String _NumeroSerie;
        partial void OnNumeroSerieChanging(global::System.String value);
        partial void OnNumeroSerieChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true, "Titulo");
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Autor
        {
            get
            {
                return _Autor;
            }
            set
            {
                OnAutorChanging(value);
                ReportPropertyChanging("Autor");
                _Autor = StructuralObject.SetValidValue(value, true, "Autor");
                ReportPropertyChanged("Autor");
                OnAutorChanged();
            }
        }
        private global::System.String _Autor;
        partial void OnAutorChanging(global::System.String value);
        partial void OnAutorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AñoEdicion
        {
            get
            {
                return _AñoEdicion;
            }
            set
            {
                OnAñoEdicionChanging(value);
                ReportPropertyChanging("AñoEdicion");
                _AñoEdicion = StructuralObject.SetValidValue(value, "AñoEdicion");
                ReportPropertyChanged("AñoEdicion");
                OnAñoEdicionChanged();
            }
        }
        private Nullable<global::System.Int32> _AñoEdicion;
        partial void OnAñoEdicionChanging(Nullable<global::System.Int32> value);
        partial void OnAñoEdicionChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Libro", "Prestamo")]
        public EntityCollection<Prestamo> Prestamo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Prestamo>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Prestamo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Prestamo>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Prestamo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EV4CristopherPeregrinModel", Name="Prestamo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prestamo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Prestamo.
        /// </summary>
        /// <param name="prestamoID">Valor inicial de la propiedad PrestamoID.</param>
        public static Prestamo CreatePrestamo(global::System.Int32 prestamoID)
        {
            Prestamo prestamo = new Prestamo();
            prestamo.PrestamoID = prestamoID;
            return prestamo;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrestamoID
        {
            get
            {
                return _PrestamoID;
            }
            set
            {
                if (_PrestamoID != value)
                {
                    OnPrestamoIDChanging(value);
                    ReportPropertyChanging("PrestamoID");
                    _PrestamoID = StructuralObject.SetValidValue(value, "PrestamoID");
                    ReportPropertyChanged("PrestamoID");
                    OnPrestamoIDChanged();
                }
            }
        }
        private global::System.Int32 _PrestamoID;
        partial void OnPrestamoIDChanging(global::System.Int32 value);
        partial void OnPrestamoIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaPrestamo
        {
            get
            {
                return _FechaPrestamo;
            }
            set
            {
                OnFechaPrestamoChanging(value);
                ReportPropertyChanging("FechaPrestamo");
                _FechaPrestamo = StructuralObject.SetValidValue(value, "FechaPrestamo");
                ReportPropertyChanged("FechaPrestamo");
                OnFechaPrestamoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaPrestamo;
        partial void OnFechaPrestamoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaPrestamoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaDevolucion
        {
            get
            {
                return _FechaDevolucion;
            }
            set
            {
                OnFechaDevolucionChanging(value);
                ReportPropertyChanging("FechaDevolucion");
                _FechaDevolucion = StructuralObject.SetValidValue(value, "FechaDevolucion");
                ReportPropertyChanged("FechaDevolucion");
                OnFechaDevolucionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaDevolucion;
        partial void OnFechaDevolucionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaDevolucionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LibroID
        {
            get
            {
                return _LibroID;
            }
            set
            {
                OnLibroIDChanging(value);
                ReportPropertyChanging("LibroID");
                _LibroID = StructuralObject.SetValidValue(value, "LibroID");
                ReportPropertyChanged("LibroID");
                OnLibroIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LibroID;
        partial void OnLibroIDChanging(Nullable<global::System.Int32> value);
        partial void OnLibroIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClienteID
        {
            get
            {
                return _ClienteID;
            }
            set
            {
                OnClienteIDChanging(value);
                ReportPropertyChanging("ClienteID");
                _ClienteID = StructuralObject.SetValidValue(value, "ClienteID");
                ReportPropertyChanged("ClienteID");
                OnClienteIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ClienteID;
        partial void OnClienteIDChanging(Nullable<global::System.Int32> value);
        partial void OnClienteIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaLimite
        {
            get
            {
                return _FechaLimite;
            }
            set
            {
                OnFechaLimiteChanging(value);
                ReportPropertyChanging("FechaLimite");
                _FechaLimite = StructuralObject.SetValidValue(value, "FechaLimite");
                ReportPropertyChanged("FechaLimite");
                OnFechaLimiteChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaLimite;
        partial void OnFechaLimiteChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaLimiteChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("EV4CristopherPeregrinModel.FK_Prestamo_Cliente", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EV4CristopherPeregrinModel", "FK_Prestamo_Libro", "Libro")]
        public Libro Libro
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Libro>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Libro").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Libro>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Libro").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Libro> LibroReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Libro>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Libro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Libro>("EV4CristopherPeregrinModel.FK_Prestamo_Libro", "Libro", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
