//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CP04052015bModel", "FK_Venta_Item", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CP04052015b.Item), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CP04052015b.Venta), true)]

#endregion

namespace CP04052015b
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CP04052015bEntidades : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CP04052015bEntidades usando la cadena de conexión encontrada en la sección 'CP04052015bEntidades' del archivo de configuración de la aplicación.
        /// </summary>
        public CP04052015bEntidades() : base("name=CP04052015bEntidades", "CP04052015bEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CP04052015bEntidades.
        /// </summary>
        public CP04052015bEntidades(string connectionString) : base(connectionString, "CP04052015bEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CP04052015bEntidades.
        /// </summary>
        public CP04052015bEntidades(EntityConnection connection) : base(connection, "CP04052015bEntidades")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Item> Item
        {
            get
            {
                if ((_Item == null))
                {
                    _Item = base.CreateObjectSet<Item>("Item");
                }
                return _Item;
            }
        }
        private ObjectSet<Item> _Item;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Venta> Venta
        {
            get
            {
                if ((_Venta == null))
                {
                    _Venta = base.CreateObjectSet<Venta>("Venta");
                }
                return _Venta;
            }
        }
        private ObjectSet<Venta> _Venta;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Item. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Venta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVenta(Venta venta)
        {
            base.AddObject("Venta", venta);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CP04052015bModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Item.
        /// </summary>
        /// <param name="itemID">Valor inicial de la propiedad itemID.</param>
        public static Item CreateItem(global::System.Int32 itemID)
        {
            Item item = new Item();
            item.itemID = itemID;
            return item;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 itemID
        {
            get
            {
                return _itemID;
            }
            set
            {
                if (_itemID != value)
                {
                    OnitemIDChanging(value);
                    ReportPropertyChanging("itemID");
                    _itemID = StructuralObject.SetValidValue(value, "itemID");
                    ReportPropertyChanged("itemID");
                    OnitemIDChanged();
                }
            }
        }
        private global::System.Int32 _itemID;
        partial void OnitemIDChanging(global::System.Int32 value);
        partial void OnitemIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, "Precio");
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private Nullable<global::System.Int32> _Precio;
        partial void OnPrecioChanging(Nullable<global::System.Int32> value);
        partial void OnPrecioChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CP04052015bModel", "FK_Venta_Item", "Venta")]
        public EntityCollection<Venta> Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("CP04052015bModel.FK_Venta_Item", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("CP04052015bModel.FK_Venta_Item", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CP04052015bModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Venta.
        /// </summary>
        /// <param name="ventaID">Valor inicial de la propiedad VentaID.</param>
        public static Venta CreateVenta(global::System.Int32 ventaID)
        {
            Venta venta = new Venta();
            venta.VentaID = ventaID;
            return venta;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VentaID
        {
            get
            {
                return _VentaID;
            }
            set
            {
                if (_VentaID != value)
                {
                    OnVentaIDChanging(value);
                    ReportPropertyChanging("VentaID");
                    _VentaID = StructuralObject.SetValidValue(value, "VentaID");
                    ReportPropertyChanged("VentaID");
                    OnVentaIDChanged();
                }
            }
        }
        private global::System.Int32 _VentaID;
        partial void OnVentaIDChanging(global::System.Int32 value);
        partial void OnVentaIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pago
        {
            get
            {
                return _Pago;
            }
            set
            {
                OnPagoChanging(value);
                ReportPropertyChanging("Pago");
                _Pago = StructuralObject.SetValidValue(value, "Pago");
                ReportPropertyChanged("Pago");
                OnPagoChanged();
            }
        }
        private Nullable<global::System.Int32> _Pago;
        partial void OnPagoChanging(Nullable<global::System.Int32> value);
        partial void OnPagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vuelto
        {
            get
            {
                return _Vuelto;
            }
            set
            {
                OnVueltoChanging(value);
                ReportPropertyChanging("Vuelto");
                _Vuelto = StructuralObject.SetValidValue(value, "Vuelto");
                ReportPropertyChanged("Vuelto");
                OnVueltoChanged();
            }
        }
        private Nullable<global::System.Int32> _Vuelto;
        partial void OnVueltoChanging(Nullable<global::System.Int32> value);
        partial void OnVueltoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> itemID
        {
            get
            {
                return _itemID;
            }
            set
            {
                OnitemIDChanging(value);
                ReportPropertyChanging("itemID");
                _itemID = StructuralObject.SetValidValue(value, "itemID");
                ReportPropertyChanged("itemID");
                OnitemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _itemID;
        partial void OnitemIDChanging(Nullable<global::System.Int32> value);
        partial void OnitemIDChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CP04052015bModel", "FK_Venta_Item", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("CP04052015bModel.FK_Venta_Item", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("CP04052015bModel.FK_Venta_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("CP04052015bModel.FK_Venta_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("CP04052015bModel.FK_Venta_Item", "Item", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
