//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BD20150926Model", "FK_Carrera_ToTable", "Area", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(_20150926.Area), "Carrera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(_20150926.Carrera), true)]

#endregion

namespace _20150926
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntidadesBD20150926 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntidadesBD20150926 usando la cadena de conexión encontrada en la sección 'EntidadesBD20150926' del archivo de configuración de la aplicación.
        /// </summary>
        public EntidadesBD20150926() : base("name=EntidadesBD20150926", "EntidadesBD20150926")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadesBD20150926.
        /// </summary>
        public EntidadesBD20150926(string connectionString) : base(connectionString, "EntidadesBD20150926")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadesBD20150926.
        /// </summary>
        public EntidadesBD20150926(EntityConnection connection) : base(connection, "EntidadesBD20150926")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Area> Area
        {
            get
            {
                if ((_Area == null))
                {
                    _Area = base.CreateObjectSet<Area>("Area");
                }
                return _Area;
            }
        }
        private ObjectSet<Area> _Area;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Carrera> Carrera
        {
            get
            {
                if ((_Carrera == null))
                {
                    _Carrera = base.CreateObjectSet<Carrera>("Carrera");
                }
                return _Carrera;
            }
        }
        private ObjectSet<Carrera> _Carrera;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Area. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToArea(Area area)
        {
            base.AddObject("Area", area);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Carrera. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCarrera(Carrera carrera)
        {
            base.AddObject("Carrera", carrera);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD20150926Model", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Area.
        /// </summary>
        /// <param name="areaID">Valor inicial de la propiedad AreaID.</param>
        public static Area CreateArea(global::System.Int32 areaID)
        {
            Area area = new Area();
            area.AreaID = areaID;
            return area;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AreaID
        {
            get
            {
                return _AreaID;
            }
            set
            {
                if (_AreaID != value)
                {
                    OnAreaIDChanging(value);
                    ReportPropertyChanging("AreaID");
                    _AreaID = StructuralObject.SetValidValue(value, "AreaID");
                    ReportPropertyChanged("AreaID");
                    OnAreaIDChanged();
                }
            }
        }
        private global::System.Int32 _AreaID;
        partial void OnAreaIDChanging(global::System.Int32 value);
        partial void OnAreaIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Encargado
        {
            get
            {
                return _Encargado;
            }
            set
            {
                OnEncargadoChanging(value);
                ReportPropertyChanging("Encargado");
                _Encargado = StructuralObject.SetValidValue(value, true, "Encargado");
                ReportPropertyChanged("Encargado");
                OnEncargadoChanged();
            }
        }
        private global::System.String _Encargado;
        partial void OnEncargadoChanging(global::System.String value);
        partial void OnEncargadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD20150926Model", "FK_Carrera_ToTable", "Carrera")]
        public EntityCollection<Carrera> Carrera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Carrera>("BD20150926Model.FK_Carrera_ToTable", "Carrera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Carrera>("BD20150926Model.FK_Carrera_ToTable", "Carrera", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD20150926Model", Name="Carrera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Carrera : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Carrera.
        /// </summary>
        /// <param name="carreraID">Valor inicial de la propiedad CarreraID.</param>
        public static Carrera CreateCarrera(global::System.Int32 carreraID)
        {
            Carrera carrera = new Carrera();
            carrera.CarreraID = carreraID;
            return carrera;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarreraID
        {
            get
            {
                return _CarreraID;
            }
            set
            {
                if (_CarreraID != value)
                {
                    OnCarreraIDChanging(value);
                    ReportPropertyChanging("CarreraID");
                    _CarreraID = StructuralObject.SetValidValue(value, "CarreraID");
                    ReportPropertyChanged("CarreraID");
                    OnCarreraIDChanged();
                }
            }
        }
        private global::System.Int32 _CarreraID;
        partial void OnCarreraIDChanging(global::System.Int32 value);
        partial void OnCarreraIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Duracion
        {
            get
            {
                return _Duracion;
            }
            set
            {
                OnDuracionChanging(value);
                ReportPropertyChanging("Duracion");
                _Duracion = StructuralObject.SetValidValue(value, "Duracion");
                ReportPropertyChanged("Duracion");
                OnDuracionChanged();
            }
        }
        private Nullable<global::System.Int32> _Duracion;
        partial void OnDuracionChanging(Nullable<global::System.Int32> value);
        partial void OnDuracionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AreaID
        {
            get
            {
                return _AreaID;
            }
            set
            {
                OnAreaIDChanging(value);
                ReportPropertyChanging("AreaID");
                _AreaID = StructuralObject.SetValidValue(value, "AreaID");
                ReportPropertyChanged("AreaID");
                OnAreaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AreaID;
        partial void OnAreaIDChanging(Nullable<global::System.Int32> value);
        partial void OnAreaIDChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD20150926Model", "FK_Carrera_ToTable", "Area")]
        public Area Area
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("BD20150926Model.FK_Carrera_ToTable", "Area").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("BD20150926Model.FK_Carrera_ToTable", "Area").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Area> AreaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Area>("BD20150926Model.FK_Carrera_ToTable", "Area");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Area>("BD20150926Model.FK_Carrera_ToTable", "Area", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
