//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Ejemplo01
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntidadesEjemplo01 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntidadesEjemplo01 usando la cadena de conexión encontrada en la sección 'EntidadesEjemplo01' del archivo de configuración de la aplicación.
        /// </summary>
        public EntidadesEjemplo01() : base("name=EntidadesEjemplo01", "EntidadesEjemplo01")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadesEjemplo01.
        /// </summary>
        public EntidadesEjemplo01(string connectionString) : base(connectionString, "EntidadesEjemplo01")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntidadesEjemplo01.
        /// </summary>
        public EntidadesEjemplo01(EntityConnection connection) : base(connection, "EntidadesEjemplo01")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Auto> Auto
        {
            get
            {
                if ((_Auto == null))
                {
                    _Auto = base.CreateObjectSet<Auto>("Auto");
                }
                return _Auto;
            }
        }
        private ObjectSet<Auto> _Auto;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Auto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuto(Auto auto)
        {
            base.AddObject("Auto", auto);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Ejemplo01Model", Name="Auto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Auto.
        /// </summary>
        /// <param name="autoID">Valor inicial de la propiedad AutoID.</param>
        public static Auto CreateAuto(global::System.Int32 autoID)
        {
            Auto auto = new Auto();
            auto.AutoID = autoID;
            return auto;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                if (_AutoID != value)
                {
                    OnAutoIDChanging(value);
                    ReportPropertyChanging("AutoID");
                    _AutoID = StructuralObject.SetValidValue(value, "AutoID");
                    ReportPropertyChanged("AutoID");
                    OnAutoIDChanged();
                }
            }
        }
        private global::System.Int32 _AutoID;
        partial void OnAutoIDChanging(global::System.Int32 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, true, "Marca");
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, true, "Modelo");
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                OnPatenteChanging(value);
                ReportPropertyChanging("Patente");
                _Patente = StructuralObject.SetValidValue(value, true, "Patente");
                ReportPropertyChanged("Patente");
                OnPatenteChanged();
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();

        #endregion

    }

    #endregion

}
